# https://github.com/docker/awesome-compose/tree/master/nginx-golang-postgres

version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt