definitions:
  handler.createTurnamentRequest:
    properties:
      name:
        example: Tournament name
        type: string
    type: object
  handler.customUser:
    properties:
      firstname:
        example: giorgio
        type: string
      lastname:
        example: rossi
        type: string
      mail:
        example: giorossi@mail.it
        type: string
      password:
        example: "1234"
        type: string
      username:
        example: gio
        type: string
    type: object
  handler.loginResponseType:
    properties:
      message:
        example: Login successful
        type: string
      user:
        $ref: '#/definitions/handler.loginResponseUser'
    type: object
  handler.loginResponseUser:
    properties:
      email:
        example: giorossi@mail.it
        type: string
      id:
        example: 1
        type: integer
      token:
        type: string
      username:
        example: gio
        type: string
    type: object
  handler.loginUserType:
    properties:
      password:
        example: "1234"
        type: string
      username:
        example: gio
        type: string
    type: object
  sql.NullInt64:
    properties:
      int64:
        type: integer
      valid:
        description: Valid is true if Int64 is not NULL
        type: boolean
    type: object
  types.FutureTurn:
    properties:
      can_double:
        description: True if the player can double the red dice
        type: boolean
      dices:
        items:
          type: integer
        type: array
      possible_moves:
        items:
          items:
            $ref: '#/definitions/types.Move'
          type: array
        type: array
    type: object
  types.LeaderBoardEntry:
    properties:
      lose:
        example: 1
        type: integer
      user:
        example: Giorgio
        type: string
      win:
        example: 1
        type: integer
    type: object
  types.Move:
    properties:
      from:
        example: 1
        type: integer
      to:
        example: 2
        type: integer
    type: object
  types.NewGame:
    properties:
      dices_p1:
        items:
          type: integer
        type: array
      dices_p2:
        items:
          type: integer
        type: array
      game:
        $ref: '#/definitions/types.ReturnGame'
    type: object
  types.ReturnGame:
    properties:
      current_player:
        example: p1
        type: string
      double_owner:
        example: all
        type: string
      double_value:
        example: 1
        type: integer
      elo1:
        example: 1000
        type: integer
      elo2:
        example: 1000
        type: integer
      end:
        example: "2021-01-01T00:00:00Z"
        type: string
      game_type:
        example: online
        type: string
      id:
        type: integer
      p1checkers:
        description: arr[0] is bar
        items:
          type: integer
        type: array
      p2checkers:
        description: arr[0] is bar
        items:
          type: integer
        type: array
      player1:
        description: Username of the player
        example: Giorgio
        type: string
      player2:
        example: Mario
        type: string
      start:
        example: "2021-01-01T00:00:00Z"
        type: string
      status:
        example: open
        type: string
      tournament:
        $ref: '#/definitions/sql.NullInt64'
      want_to_double:
        example: false
        type: boolean
    type: object
  types.ReturnTournament:
    properties:
      creation_date:
        example: "2021-09-01T00:00:00Z"
        type: string
      games:
        items:
          $ref: '#/definitions/types.ReturnGame'
        type: array
      id:
        example: 1
        type: integer
      leader_board:
        items:
          $ref: '#/definitions/types.LeaderBoardEntry'
        type: array
      name:
        example: Tournament name
        type: string
      owner:
        example: Giorgio
        type: string
      status:
        example: open
        type: string
      users:
        example:
        - giorgio
        - diego
        - marco
        items:
          type: string
        type: array
    type: object
  types.TournamentInfo:
    properties:
      creation_date:
        example: "2021-09-01T00:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Tournament name
        type: string
      owner:
        example: Giorgio
        type: string
      user_number:
        example: 3
        type: integer
    type: object
  types.User:
    properties:
      elo:
        example: 1000
        type: integer
      firstname:
        example: giorgio
        type: string
      id:
        example: 1
        type: integer
      is_bot:
        example: false
        type: boolean
      lastname:
        example: rossi
        type: string
      mail:
        example: giorossi@mail.it
        type: string
      username:
        example: gio
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with a user
      parameters:
      - description: username and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.loginUserType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.loginResponseType'
      summary: Login
      tags:
      - authentication
  /logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: Logged out successfully
        "401":
          description: Unauthorized
        "500":
          description: Logout failed
      summary: Logout
      tags:
      - authentication
  /play:
    delete:
      consumes:
      - application/json
      description: Surrend to current game
      produces:
      - application/json
      responses:
        "201":
          description: Surrended
        "404":
          description: Not in a game
      summary: Surrend to current game
      tags:
      - play
    get:
      consumes:
      - application/json
      description: Get current game
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ReturnGame'
        "404":
          description: Game not found
      summary: Get current game
      tags:
      - play
  /play/bot/easy:
    get:
      consumes:
      - application/json
      description: Create a game against an easy bot
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.NewGame'
        "400":
          description: Not in a game or double not possible
      summary: Create a game against an easy bot
      tags:
      - play
  /play/bot/hard:
    get:
      consumes:
      - application/json
      description: Create a game against an hard bot
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.NewGame'
        "400":
          description: Not in a game or double not possible
      summary: Create a game against an hard bot
      tags:
      - play
  /play/bot/medium:
    get:
      consumes:
      - application/json
      description: Create a game against an medium bot
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.NewGame'
        "400":
          description: Not in a game or double not possible
      summary: Create a game against an medium bot
      tags:
      - play
  /play/double:
    delete:
      consumes:
      - application/json
      description: Refuse the double
      produces:
      - application/json
      responses:
        "201":
          description: Double refused
        "400":
          description: Not in a game or can't refuse double
      summary: Refuse the double
      tags:
      - play
    post:
      consumes:
      - application/json
      description: The player want to double
      produces:
      - application/json
      responses:
        "201":
          description: Value of the red dice after the double
          schema:
            type: integer
        "400":
          description: Not in a game or double not possible
      summary: The player want to double
      tags:
      - play
    put:
      consumes:
      - application/json
      description: Accept the double
      produces:
      - application/json
      responses:
        "201":
          description: Double accepted
        "400":
          description: Not in a game or double not possible
      summary: Accept the double
      tags:
      - play
  /play/last/winner:
    get:
      consumes:
      - application/json
      description: Get last fame status
      produces:
      - application/json
      responses:
        "200":
          description: Status of the last game
          schema:
            type: string
        "404":
          description: No games or no status found
      summary: Get last game status
      tags:
      - play
  /play/local:
    get:
      consumes:
      - application/json
      description: Create a local game for playing locally in the same device
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.NewGame'
        "400":
          description: Already in a game
      summary: Create a local game
      tags:
      - play
  /play/moves:
    get:
      consumes:
      - application/json
      description: Get possible moves for next turn
      produces:
      - application/json
      responses:
        "200":
          description: Dice with all possible moves and the ability to double
          schema:
            $ref: '#/definitions/types.FutureTurn'
        "400":
          description: Not in a game, not your turn or double requested
      summary: Get possible moves for next turn
      tags:
      - play
    post:
      consumes:
      - application/json
      description: Play all the moves for the current turn
      parameters:
      - description: Moves to play
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/types.Move'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Moves played
        "400":
          description: Moves not legal, not your turn or not in a game
      summary: Play all the moves for the current turn
      tags:
      - play
  /play/search:
    delete:
      consumes:
      - application/json
      description: Stop a running matchmaking search
      produces:
      - application/json
      responses:
        "204":
          description: Search stopped
        "400":
          description: Not searching
      summary: Stop a running matchmaking search
      tags:
      - play
    get:
      consumes:
      - application/json
      description: Start a matchmaking search for a new game
      produces:
      - application/json
      responses:
        "201":
          description: Search started
        "400":
          description: Already searching or in a game
      summary: Start a matchmaking search for a new game
      tags:
      - play
  /register:
    post:
      consumes:
      - application/json
      description: Register new user
      parameters:
      - description: user with password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.customUser'
      produces:
      - application/json
      responses:
        "201":
          description: user created
          schema:
            $ref: '#/definitions/types.User'
      summary: Register new user
      tags:
      - authentication
  /session:
    get:
      consumes:
      - application/json
      description: Get auth session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
        "500":
          description: error
      summary: Get current auth session
      tags:
      - authentication
  /tournament/{tournament_id}:
    delete:
      consumes:
      - application/json
      description: Leave a tournament if the tournament is not started
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: leaved
        "400":
          description: you are the owner
        "404":
          description: tournament not found
      summary: Leave a tournament
      tags:
      - tournament
    get:
      consumes:
      - application/json
      description: Get a tournament
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ReturnTournament'
        "404":
          description: tournament not found
      summary: Get a tournament
      tags:
      - tournament
    post:
      consumes:
      - application/json
      description: Join a tournament
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ReturnTournament'
        "400":
          description: alredy in a tournament
        "404":
          description: tournament not found
      summary: Join a tournament
      tags:
      - tournament
  /tournament/{tournament_id}/cancel:
    post:
      consumes:
      - application/json
      description: Cancel a waiting tournament, only the owner can cancel it
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: tournament canceled
        "400":
          description: you are not the owner
        "404":
          description: tournament not found
      summary: Cancel a tournament
      tags:
      - tournament
  /tournament/{tournament_id}/start:
    post:
      consumes:
      - application/json
      description: Start a tournament, only the owner can start it
      parameters:
      - description: Tournament ID
        in: path
        name: tournament_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: tournament started
        "400":
          description: you are not the owner
        "404":
          description: tournament not found
      summary: Start a tournament
      tags:
      - tournament
  /tournament/create:
    post:
      consumes:
      - application/json
      description: Create a new tournament
      parameters:
      - description: createTurnamentRequest object
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.createTurnamentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.ReturnTournament'
        "400":
          description: bad data, tournament alredy open
        "500":
          description: internal server error
      summary: Create a new tournament
      tags:
      - tournament
  /tournament/list:
    get:
      consumes:
      - application/json
      description: List all tournaments you can access
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.TournamentInfo'
            type: array
        "500":
          description: internal server error
      summary: List all tournaments
      tags:
      - tournament
swagger: "2.0"
