definitions:
  types.FutureTurn:
    properties:
      can_double:
        description: True if the player can double the red dice
        type: boolean
      dices:
        items:
          type: integer
        type: array
      possible_moves:
        items:
          items:
            $ref: '#/definitions/types.Move'
          type: array
        type: array
    type: object
  types.Move:
    properties:
      from:
        example: 1
        type: integer
      to:
        example: 2
        type: integer
    type: object
  types.NewGame:
    properties:
      dices_p1:
        items:
          type: integer
        type: array
      dices_p2:
        items:
          type: integer
        type: array
      game:
        $ref: '#/definitions/types.ReturnGame'
    type: object
  types.ReturnGame:
    properties:
      current_player:
        type: string
      double_owner:
        type: string
      double_value:
        type: integer
      elo1:
        type: integer
      elo2:
        type: integer
      end:
        type: string
      id:
        type: integer
      p1checkers:
        description: arr[0] is bar
        items:
          type: integer
        type: array
      p2checkers:
        description: arr[0] is bar
        items:
          type: integer
        type: array
      player1:
        description: Username of the player
        type: string
      player2:
        type: string
      start:
        type: string
      status:
        type: string
      want_to_double:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /play:
    delete:
      consumes:
      - application/json
      description: Surrend to current game
      produces:
      - application/json
      responses:
        "201":
          description: Surrended
        "404":
          description: Not in a game
      summary: Surrend to current game
      tags:
      - play
    get:
      consumes:
      - application/json
      description: Get current game
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ReturnGame'
        "404":
          description: Game not found
      summary: Get current game
      tags:
      - play
  /play/double:
    delete:
      consumes:
      - application/json
      description: Refuse the double
      produces:
      - application/json
      responses:
        "201":
          description: Double refused
        "400":
          description: Not in a game or can't refuse double
      summary: Refuse the double
      tags:
      - play
    post:
      consumes:
      - application/json
      description: The player want to double
      produces:
      - application/json
      responses:
        "201":
          description: Value of the red dice after the double
          schema:
            type: integer
        "400":
          description: Not in a game or double not possible
      summary: The player want to double
      tags:
      - play
    put:
      consumes:
      - application/json
      description: Accept the double
      produces:
      - application/json
      responses:
        "201":
          description: Double accepted
        "400":
          description: Not in a game or double not possible
      summary: Accept the double
      tags:
      - play
  /play/local:
    get:
      consumes:
      - application/json
      description: Create a local game for playing locally in the same device
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.NewGame'
        "400":
          description: Already in a game
      summary: Create a local game
      tags:
      - play
  /play/moves:
    get:
      consumes:
      - application/json
      description: Get possible moves for next turn
      produces:
      - application/json
      responses:
        "200":
          description: Dice with all possible moves and the ability to double
          schema:
            $ref: '#/definitions/types.FutureTurn'
        "400":
          description: Not in a game, not your turn or double requested
      summary: Get possible moves for next turn
      tags:
      - play
    post:
      consumes:
      - application/json
      description: Play all the moves for the current turn
      parameters:
      - description: Moves to play
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/types.Move'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Moves played
        "400":
          description: Moves not legal, not your turn or not in a game
      summary: Play all the moves for the current turn
      tags:
      - play
  /play/search:
    delete:
      consumes:
      - application/json
      description: Stop a running matchmaking search
      produces:
      - application/json
      responses:
        "204":
          description: Search stopped
        "400":
          description: Not searching
      summary: Stop a running matchmaking search
      tags:
      - play
    get:
      consumes:
      - application/json
      description: Start a matchmaking search for a new game
      produces:
      - application/json
      responses:
        "201":
          description: Search started
        "400":
          description: Already searching or in a game
      summary: Start a matchmaking search for a new game
      tags:
      - play
swagger: "2.0"
